/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'sender' : Principal,
  'isEdited' : boolean,
  'timestamp' : bigint,
}
export interface UserProfile {
  'status' : string,
  'username' : string,
  'isActive' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGroupMember' : ActorMethod<[string, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignGroupAdmin' : ActorMethod<[string, Principal], undefined>,
  'createChat' : ActorMethod<
    [Array<Principal>, boolean, [] | [string], [] | [ExternalBlob]],
    string
  >,
  'deleteConversation' : ActorMethod<[string], undefined>,
  'deleteMessage' : ActorMethod<[string, bigint, boolean], undefined>,
  'disableUser' : ActorMethod<[Principal], undefined>,
  'editMessage' : ActorMethod<[string, bigint, string], undefined>,
  'enableUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[string], Array<Message>>,
  'getConversations' : ActorMethod<
    [],
    Array<
      {
        'messages' : Array<Message>,
        'groupAvatar' : [] | [ExternalBlob],
        'chatId' : string,
        'groupName' : [] | [string],
      }
    >
  >,
  'getTotalMessageCount' : ActorMethod<[], bigint>,
  'getTotalUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGroupMember' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMessages' : ActorMethod<[string, string], Array<Message>>,
  'searchUserByUsername' : ActorMethod<[string], [] | [Principal]>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'updateGroupSettings' : ActorMethod<
    [string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];